In [4]:
import numpy as np

In [17]:
a = np.array([
    [
        [
           [1,2],
            [11,]
        ],
        
        [
            [9,10],
            [7,8]
        ]
    ],
    
    [
        [
           [3,4],
            [11,12]
        ],
        
        [
            [5,6],
            [15,16]
        ]
    ]

])


In [18]:
print(a.shape)

(2, 2, 2, 2)


In [19]:
print(a.shape)

(2, 2, 2, 2)


In [20]:
print(a.argmax(axis=0))

[[[1 1]
  [0 0]]

 [[0 0]
  [1 1]]]


In [36]:
a= np.array([[1,2],[3,4]])  

In [38]:
a.sum(axis = 0)

array([4, 6])

In [39]:

a = np.array([
              [
                  [1, 5, 5, 2],
                  [9, -6, 2, 8],
                  [-3, 7, -9, 1]
              ],
 
              [
                  [-1, 7, -5, 2],
                  [9, 6, 2, 8],
                  [3, 7, 9, 1]
              ],
            
             [
                  [21, 6, -5, 2],
                  [9, 36, 2, 8],
                  [3, 7, 79, 1]
              ]
])


In [47]:
a.shape

(3, 3, 4)

In [48]:
np.argmax(a, axis=1)

array([[1, 2, 0, 1],
       [1, 0, 2, 1],
       [0, 1, 2, 1]], dtype=int64)

In [28]:
import tensorflow as tf

In [29]:
 tf.test.gpu_device_name()

'/device:GPU:0'

In [30]:
a = tf.Variable(a)

In [32]:
with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(a.eval())
        

[[[[ 1  2]
   [11 12]]

  [[ 9 10]
   [ 7  8]]]


 [[[ 3  4]
   [ 1  2]]

  [[ 5  6]
   [15 16]]]]


In [86]:
c = tf.argmax(a, axis=-1)

In [87]:
with tf.Session() as sess:
    print(c.eval())

[[1 0 1]
 [1 0 2]
 [0 1 2]]


In [37]:
import numpy as np

In [57]:
c = np.array([
    [True,False],[True,True]
])


In [58]:
a = np.array([
    [1,2],
    [3,4]
])

In [62]:
print(a.argsort(0))

[[0 0]
 [1 1]]


In [65]:
x = np.array([3, 1, 2])

In [66]:
np.argsort(-x)

array([0, 2, 1], dtype=int64)