In [7]:
import tensorflow as tf

In [8]:
import cv2

In [9]:
tf.__version__ #1.12

'1.12.0'

In [10]:
tf.test.is_gpu_available()

True

In [1]:
import numpy as np

In [5]:
t = np.np.array([np.arange(5)] * 5 * 4)

In [6]:
print(t)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [7]:
print(t.shape)

(20, 5)
